version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - grobid-service



  grobid-service:
    image: lfoppiano/grobid:0.8.0
    ports:
      - "8070:8070"
    init: true
    ulimits:
      core:
        soft: 0
        hard: 0