version: '3.8'

services:
  # app:
  #   build: .
  #   ports:
  #     - "8000:8000"
  #   env_file:
  #     - .env  # Path to your .env file containing the OPENAI_API_KEY
  #   depends_on:
  #     - grobid-service

  grobid-service:
    image: lfoppiano/grobid:0.8.0
    ports:
      - "8070:8070"
    init: true
    ulimits:
      core:
        soft: 0
        hard: 0